"""empty message

Revision ID: a5e2f464b3f9
Revises: 30810d16b7a8
Create Date: 2019-06-08 19:54:25.613397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e2f464b3f9'
down_revision = '30810d16b7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'user_id')
    # ### end Alembic commands ###
